ALTER TABLE public.job_logs
ADD COLUMN IF NOT EXISTS had_reconnect BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS reconnect_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS used_ferry BOOLEAN DEFAULT false;
